server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Todas las rutas dirigen al index.html para que el router de Angular funcione
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para las llamadas a la API
    # De esta manera, el Nginx del frontend redirige cualquier llamada /api al contenedor backend
    location /api/ {
        proxy_pass http://backend:3001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs;
    }

    # Proxies para las grabaciones y scripts si están expuestos en el backend
    location /evidencias/ {
        proxy_pass http://backend:3001/evidencias/;
    }
}
