services:
  db:
    image: mysql:8.0
    container_name: sirio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sirio_root_pass
      MYSQL_DATABASE: sirioqa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psirio_root_pass" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
